[package]
name = "zclimate"
version = "0.1.0"
authors = ["John_Bruhling"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inotify = "0.8.2"
chrono = "0.4"
