#!/bin/bash

while inotifywait -r -qq -e close_write "/home/john/zcash/src/climateusenox2.txt"
do
cp "/home/john/zcash/src/climateusenox2.txt" "/home/john/zcash/src/climateusenox3.txt"
variable=$(./climateusenox3.txt)
$variable

done

