#!/bin/bash

while inotifywait -r -qq -e close_write "/home/john/zcash/src/climateusenox4.txt"
do
cp "/home/john/zcash/src/climateusenox4.txt" "/home/john/zcash/src/climateusenox5.txt"
variable=$(./climateusenox5.txt)
$variable

done

